name: Scrape Website

on:
  workflow_dispatch: # Trigger für manuellen Start

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install packages
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        packages: |
          any::rvest

    - name: Check out repository
      uses: actions/checkout@v3

    - name: Run scrape script
      run: Rscript test_scraper_action.R

    - name: Upload results
      uses: actions/upload-artifact@v3
      with:
        name: scraped-data
        path: titles.csv
