name: Scrape Website

on:
  workflow_dispatch: # Trigger für manuellen Start

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.3.1' # Gewünschte R-Version

    - name: Install R packages
      run: |
        R -e 'install.packages("rvest")'

    - name: Run scrape script
      run: Rscript test_scraper_action.R

    - name: Upload result
      uses: actions/upload-artifact@v3
      with:
        name: scraped-data
        path: titles.csv
